### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mr-cheffy** [Emily3403/Suwudo#1]
When running the `cp` command, I get a segmentation fault error...

**Comment by Emily3403** [comment]
As described in the [Readme](https://github.com/Emily3403/Suwudo#installation), this error may arise. You can safely ignore the error.

**Comment by mr-cheffy** [comment]
@Emily3403 Just say that if there is a segmentation fault. Because that error may just appear to you when u receive segfault (because of your terminal or smt)

**Comment by Emily3403** [comment]
I mean... it is literally in the readme and the readme is 75 lines. What more do you expect?
