### ISSUE TITLE
No such file or directory: '/usr/lib/sudo/sudoers.so' on Fedora 35

### ISSUE THREAD

**Issue by latenightdef** [Emily3403/Suwudo#2]
I tried to install Suwudo on Fedora 35 and got an error.

```
cp: cannot stat '/usr/lib/sudo/sudoers.so': No such file or directory
Traceback (most recent call last):
  File "/home/sasha/git/Suwudo/./suwudo.py", line 313, in <module>
    main()
  File "/home/sasha/git/Suwudo/./suwudo.py", line 268, in main
    with open("/usr/lib/sudo/sudoers.so", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/sudo/sudoers.so'
Successfully installed!
```

Looks like sudoers.so on Fedora is located in `/usr/libexec/sudo` instead. Distro-checking for the correct install location would be nice!

**Comment by Emily3403** [comment]
Yeah, that is currently on the todo list. I just haven't gotten around to testing it out on my VM's. Will try to do it tomorrow or so.

You can patch it for now by just replacing 
```
with open("/usr/lib/sudo/sudoers.so", "rb") as f:
```
with
```
with open("/usr/libexec/sudo/sudoers.so", "rb") as f:
```

If you are using the `install.sh` you'd also have to replace it there. ^^

**Comment by Emily3403** [comment]
The installation now works with fedora, but I can't get the insults to work… I think this has something to do with the sudo binary not respecting the option. The only possiblity is, according to [this](https://www.reddit.com/r/Fedora/comments/7reji8/sudo_insults_not_working/) reddit post, to recompile and enable insults.
